name: Continuous Integration & Deployment
permissions: write-all
on:
  push:
    tags:
      - v*

jobs:
  publish-libs:
    name: Create release
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-create-release
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2

      - uses: frabert/replace-string-action@v2.3
        id: get-version-from-tag
        with:
          pattern: v(.*)
          string: ${{ github.ref_name }}
          replace-with: $1

      - uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Version ${{ steps.get-version-from-tag.outputs.replaced }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
