name: Continuous Integration & Deployment
permissions: write-all
on:
  push:
    tags:
      - v*

jobs:
  publish-libs:
    name: Create release
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-create-release
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3.3.0

      - uses: frabert/replace-string-action@v2.4
        id: get-version-from-tag
        with:
          pattern: v(.*)
          string: ${{ github.ref_name }}
          replace-with: $1

      - uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{ github.ref_name }}
          name: Version ${{ steps.get-version-from-tag.outputs.replaced }}
          token: ${{ secrets.GITHUB_TOKEN }}
